// Mock data for all entities

// Leads
export const mockLeads = [
  {
    id: 1,
    name: "Rajesh Kumar",
    email: "rajesh.kumar@example.in",
    phone: "+91 98765 43210",
    source: "Website",
    status: "New",
    date: "2023-05-18",
    project: "Parkview Residences",
    executive: "Anita Sharma",
    address: "12 MG Road, Bengaluru, Karnataka 560001",
    budget: "₹60L - ₹80L",
    requirements: "3 BHK, garden view, higher floor",
    notes:
      "Looking for a family home in a quiet area, preferably near good schools.",
  },
  {
    id: 2,
    name: "Priya Iyer",
    email: "priya.iyer@example.in",
    phone: "+91 99876 54321",
    source: "Facebook",
    status: "Contacted",
    date: "2023-05-17",
    project: "Riverside Apartments",
    executive: "Rohit Mehra",
    address: "45 Nehru Road, Pune, Maharashtra 411001",
    budget: "₹40L - ₹50L",
    requirements: "2 BHK, riverside view",
    notes: "Looking for investment. Focus on rental income.",
  },
  {
    id: 3,
    name: "Amit Verma",
    email: "amit.verma@example.in",
    phone: "+91 91234 56789",
    source: "Referral",
    status: "Site Visit",
    date: "2023-05-16",
    project: "Parkview Residences",
    executive: "Anita Sharma",
    address: "88 Residency Lane, Noida, Uttar Pradesh 201301",
    budget: "₹70L - ₹90L",
    requirements: "4 BHK, premium amenities",
    notes: "Family of four looking for a long-term residence.",
  },
  {
    id: 4,
    name: "Sneha Reddy",
    email: "sneha.reddy@example.in",
    phone: "+91 93456 78901",
    source: "Instagram",
    status: "Negotiation",
    date: "2023-05-15",
    project: "Skyline Towers",
    executive: "Meena Joshi",
    address: "23 Jubilee Hills, Hyderabad, Telangana 500033",
    budget: "₹90L - ₹1.2Cr",
    requirements: "3 BHK, high floor, city view",
    notes:
      "Working professional. Prefers modern design and smart home features.",
  },
  {
    id: 5,
    name: "Manoj Desai",
    email: "manoj.desai@example.in",
    phone: "+91 98712 34567",
    source: "Google",
    status: "Won",
    date: "2023-05-14",
    project: "Riverside Apartments",
    executive: "Rohit Mehra",
    address: "67 Ashok Nagar, Ahmedabad, Gujarat 380015",
    budget: "₹50L - ₹60L",
    requirements: "2 BHK, modern amenities",
    notes: "First-time home buyer. Pre-approved for home loan.",
  },
  {
    id: 6,
    name: "Neha Sharma",
    email: "neha.sharma@example.in",
    phone: "+91 90012 34567",
    source: "Website",
    status: "New",
    date: "2023-05-13",
    project: "Skyline Towers",
    executive: "Meena Joshi",
    address: "120 Banjara Hills, Hyderabad, Telangana 500034",
    budget: "₹80L - ₹1Cr",
    requirements: "3 BHK, pet-friendly",
    notes: "Has two dogs. Needs pet facilities and parks nearby.",
  },
  {
    id: 7,
    name: "Arjun Nair",
    email: "arjun.nair@example.in",
    phone: "+91 98564 32710",
    source: "Referral",
    status: "Contacted",
    date: "2023-05-12",
    project: "Parkview Residences",
    executive: "Anita Sharma",
    address: "34 Sector 62, Noida, Uttar Pradesh 201309",
    budget: "₹60L - ₹70L",
    requirements: "2 BHK, study room",
    notes: "Works remotely. Needs dedicated office space.",
  },
  {
    id: 8,
    name: "Meera Banerjee",
    email: "meera.banerjee@example.in",
    phone: "+91 97654 21098",
    source: "Facebook",
    status: "Lost",
    date: "2023-05-11",
    project: "Riverside Apartments",
    executive: "Rohit Mehra",
    address: "59 Lake Road, Kolkata, West Bengal 700029",
    budget: "₹40L - ₹50L",
    requirements: "2 BHK, ground floor",
    notes: "Senior citizen couple. Needs accessible design.",
  },
];


// Lead Activities
export const mockLeadActivities = [
  {
    id: 1,
    leadId: 1,
    type: "note",
    content: "Initial contact with the client. Showed interest in 3 BHK units.",
    date: "2023-05-18",
    time: "10:30 AM",
    user: "Alex Johnson",
  },
  {
    id: 2,
    leadId: 1,
    type: "call",
    content:
      "Followed up on initial inquiry. Client has requested floor plans for Parkview Residences.",
    date: "2023-05-19",
    time: "2:15 PM",
    user: "Alex Johnson",
  },
  {
    id: 3,
    leadId: 1,
    type: "email",
    content:
      "Sent floor plans and pricing details for Parkview Residences 3 BHK units.",
    date: "2023-05-19",
    time: "3:30 PM",
    user: "Alex Johnson",
  },
  {
    id: 4,
    leadId: 1,
    type: "visit",
    content: "Scheduled site visit for May 22nd at 11:00 AM.",
    date: "2023-05-20",
    time: "11:45 AM",
    user: "Alex Johnson",
  },
  {
    id: 5,
    leadId: 2,
    type: "note",
    content:
      "Client interested in investment properties with good rental yield.",
    date: "2023-05-17",
    time: "9:30 AM",
    user: "Michael Chen",
  },
  {
    id: 6,
    leadId: 3,
    type: "call",
    content: "Discussed premium amenities at Parkview Residences.",
    date: "2023-05-16",
    time: "1:45 PM",
    user: "Alex Johnson",
  },
];

// Projects
export const mockProjects = [
  {
    id: 1,
    name: "Parkview Residences",
    image:
      "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=800&q=80",
    description:
      "Luxury residential apartments in Downtown with stunning park views. Features include premium finishes, rooftop garden, fitness center, and 24/7 security.",
    location: "Downtown, Metro City",
    type: "Residential",
    unit: 120,
    available: 45,
    booked: 35,
    sold: 40,
    reraId: "RERA12345",
    completionDate: "2024-06-30",
    launchDate: "2022-04-15",
    status: "Active",
    amenities: [
      "Swimming Pool",
      "Fitness Center",
      "Clubhouse",
      "Rooftop Garden",
      "Children's Play Area",
      "24/7 Security",
      "Covered Parking",
      "Visitor Parking",
    ],
    floorPlans: [
      {
        id: 1,
        projectId: 1,
        type: "1 BHK",
        size: "650-750 sq ft",
        startingPrice: "$250,000",
        available: 15,
      },
      {
        id: 2,
        projectId: 1,
        type: "2 BHK",
        size: "950-1100 sq ft",
        startingPrice: "$380,000",
        available: 20,
      },
      {
        id: 3,
        projectId: 1,
        type: "3 BHK",
        size: "1350-1500 sq ft",
        startingPrice: "$520,000",
        available: 10,
      },
    ],
    units: [
      {
        id: 1,
        unitNo: "A-101",
        type: "1 BHK",
        floor: 1,
        block: "A",
        size: "680 sq ft",
        price: "$255,000",
        status: "Available",
        facing: "Park",
      },
      {
        id: 2,
        unitNo: "A-102",
        type: "2 BHK",
        floor: 1,
        block: "A",
        size: "980 sq ft",
        price: "$385,000",
        status: "Booked",
        facing: "Street",
      },
      {
        id: 3,
        unitNo: "A-201",
        type: "2 BHK",
        floor: 2,
        block: "A",
        size: "1000 sq ft",
        price: "$390,000",
        status: "Available",
        facing: "Park",
      },
      {
        id: 4,
        unitNo: "A-202",
        type: "3 BHK",
        floor: 2,
        block: "A",
        size: "1400 sq ft",
        price: "$530,000",
        status: "Sold",
        facing: "Street",
      },
      {
        id: 5,
        unitNo: "B-101",
        type: "1 BHK",
        floor: 1,
        block: "B",
        size: "700 sq ft",
        price: "$260,000",
        status: "Available",
        facing: "Garden",
      },
    ],
    documents: [
      {
        id: 1,
        name: "Floor Plan.pdf",
        type: "Floor Plan",
        size: "2.4 MB",
        uploadedOn: "2022-04-20",
        uploadedBy: "Admin",
      },
      {
        id: 2,
        name: "RERA Certificate.pdf",
        type: "Legal",
        size: "1.1 MB",
        uploadedOn: "2022-04-15",
        uploadedBy: "Admin",
      },
      {
        id: 3,
        name: "Site Photos.zip",
        type: "Photos",
        size: "15.8 MB",
        uploadedOn: "2022-05-10",
        uploadedBy: "Alex Johnson",
      },
      {
        id: 4,
        name: "Brochure.pdf",
        type: "Marketing",
        size: "4.2 MB",
        uploadedOn: "2022-05-15",
        uploadedBy: "Marketing Team",
      },
    ],
  },
  {
    id: 2,
    name: "Riverside Apartments",
    image:
      "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=800&q=80",
    description:
      "Modern apartments by the river with serene views and eco-friendly design. Perfect for nature lovers and urban professionals.",
    location: "Riverside District, Metro City",
    type: "Residential",
    unit: 80,
    available: 25,
    booked: 30,
    sold: 25,
    reraId: "RERA67890",
    completionDate: "2025-03-31",
    launchDate: "2023-01-20",
    status: "Under Construction",
    amenities: [
      "Jogging Track",
      "Yoga Lawn",
      "Community Hall",
      "24/7 Security",
      "Basement Parking",
      "Rainwater Harvesting",
    ],
    floorPlans: [
      {
        id: 1,
        projectId: 2,
        type: "2 BHK",
        size: "900-1050 sq ft",
        startingPrice: "$310,000",
        available: 12,
      },
      {
        id: 2,
        projectId: 2,
        type: "3 BHK",
        size: "1250-1400 sq ft",
        startingPrice: "$450,000",
        available: 13,
      },
    ],
    units: [
      {
        id: 1,
        unitNo: "C-101",
        type: "2 BHK",
        floor: 1,
        block: "C",
        size: "920 sq ft",
        price: "$315,000",
        status: "Available",
        facing: "River",
      },
      {
        id: 2,
        unitNo: "C-201",
        type: "3 BHK",
        floor: 2,
        block: "C",
        size: "1300 sq ft",
        price: "$455,000",
        status: "Booked",
        facing: "Garden",
      },
    ],
    documents: [
      {
        id: 1,
        name: "Floor Plan.pdf",
        type: "Floor Plan",
        size: "3 MB",
        uploadedOn: "2023-01-22",
        uploadedBy: "Developer",
      },
    ],
  },
  {
    id: 3,
    name: "Skyline Towers",
    image:
      "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=800&q=80",
    description:
      "Iconic high-rise apartments in the heart of the business district. Premium lifestyle with panoramic city views.",
    location: "Business Bay, Metro City",
    type: "Residential",
    unit: 150,
    available: 60,
    booked: 40,
    sold: 50,
    reraId: "RERA54321",
    completionDate: "2023-12-15",
    launchDate: "2021-09-10",
    status: "Ready to Move",
    amenities: [
      "Infinity Pool",
      "Gymnasium",
      "Sky Lounge",
      "Concierge Services",
      "Business Center",
    ],
    floorPlans: [
      {
        id: 1,
        projectId: 3,
        type: "Studio",
        size: "450-550 sq ft",
        startingPrice: "$180,000",
        available: 20,
      },
      {
        id: 2,
        projectId: 3,
        type: "2 BHK",
        size: "1000-1150 sq ft",
        startingPrice: "$400,000",
        available: 40,
      },
    ],
    units: [
      {
        id: 1,
        unitNo: "T-301",
        type: "Studio",
        floor: 3,
        block: "T",
        size: "500 sq ft",
        price: "$185,000",
        status: "Available",
        facing: "City",
      },
    ],
    documents: [
      {
        id: 1,
        name: "Completion Certificate.pdf",
        type: "Legal",
        size: "1.5 MB",
        uploadedOn: "2023-12-20",
        uploadedBy: "Construction Team",
      },
    ],
  },
  {
    id: 4,
    name: "The Green Villas",
    image:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    description:
      "Premium gated villa community surrounded by greenery and tranquility. Ideal for families and peaceful living.",
    location: "Suburban Zone, Metro City",
    type: "Villa",
    unit: 50,
    available: 10,
    booked: 20,
    sold: 20,
    reraId: "RERA33445",
    completionDate: "2024-09-30",
    launchDate: "2022-06-01",
    status: "Active",
    amenities: [
      "Private Gardens",
      "Swimming Pool",
      "Jogging Path",
      "Gated Security",
      "Solar Panels",
    ],
    floorPlans: [
      {
        id: 1,
        projectId: 4,
        type: "4 BHK Villa",
        size: "2200-2500 sq ft",
        startingPrice: "$750,000",
        available: 10,
      },
    ],
    units: [
      {
        id: 1,
        unitNo: "V-1",
        type: "4 BHK Villa",
        floor: 1,
        block: "V",
        size: "2300 sq ft",
        price: "$760,000",
        status: "Available",
        facing: "North-East",
      },
    ],
    documents: [
      {
        id: 1,
        name: "Villa Layout.pdf",
        type: "Floor Plan",
        size: "5 MB",
        uploadedOn: "2022-06-05",
        uploadedBy: "Architect",
      },
    ],
  },
  {
    id: 5,
    name: "Lakeview Heights",
    image:
      "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=800&q=80",
    description:
      "Waterfront homes with scenic lake views and modern amenities. Designed for luxury and leisure.",
    location: "Lakefront, Metro City",
    type: "Residential",
    unit: 90,
    available: 30,
    booked: 30,
    sold: 30,
    reraId: "RERA11999",
    completionDate: "2025-01-10",
    launchDate: "2023-03-01",
    status: "Under Construction",
    amenities: [
      "Lake Deck",
      "Clubhouse",
      "Children’s Play Area",
      "Power Backup",
      "CCTV Surveillance",
    ],
    floorPlans: [
      {
        id: 1,
        projectId: 5,
        type: "2 BHK",
        size: "970-1100 sq ft",
        startingPrice: "$360,000",
        available: 20,
      },
      {
        id: 2,
        projectId: 5,
        type: "3 BHK",
        size: "1300-1450 sq ft",
        startingPrice: "$490,000",
        available: 10,
      },
    ],
    units: [
      {
        id: 1,
        unitNo: "L-101",
        type: "2 BHK",
        floor: 1,
        block: "L",
        size: "1000 sq ft",
        price: "$365,000",
        status: "Available",
        facing: "Lake",
      },
    ],
    documents: [
      {
        id: 1,
        name: "Master Plan.pdf",
        type: "Layout",
        size: "2 MB",
        uploadedOn: "2023-03-05",
        uploadedBy: "Admin",
      },
    ],
  },
  {
    id: 6,
    name: "Metro Central Condos",
    image:
      "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=800&q=80",
    description:
      "Affordable modern condos in the heart of Metro City. Close to metro, malls, and offices.",
    location: "Central Metro, Metro City",
    type: "Residential",
    unit: 100,
    available: 40,
    booked: 35,
    sold: 25,
    reraId: "RERA55678",
    completionDate: "2024-10-10",
    launchDate: "2022-02-25",
    status: "Active",
    amenities: [
      "Fitness Studio",
      "Multi-Purpose Hall",
      "Retail Outlets",
      "CCTV",
      "Fire Safety",
    ],
    floorPlans: [
      {
        id: 1,
        projectId: 6,
        type: "1 BHK",
        size: "600-700 sq ft",
        startingPrice: "$230,000",
        available: 25,
      },
      {
        id: 2,
        projectId: 6,
        type: "2 BHK",
        size: "850-1000 sq ft",
        startingPrice: "$340,000",
        available: 15,
      },
    ],
    units: [
      {
        id: 1,
        unitNo: "M-201",
        type: "2 BHK",
        floor: 2,
        block: "M",
        size: "900 sq ft",
        price: "$345,000",
        status: "Booked",
        facing: "South",
      },
    ],
    documents: [
      {
        id: 1,
        name: "RERA Document.pdf",
        type: "Legal",
        size: "1.2 MB",
        uploadedOn: "2022-02-26",
        uploadedBy: "Compliance",
      },
    ],
  },
];



// Units
export const mockUnits = [
  {
    id: 1,
    projectId: 1,
    unitNo: "A-101",
    type: "1 BHK",
    floor: 1,
    block: "A",
    size: "680 sq ft",
    price: "$255,000",
    status: "Available",
    facing: "Park",
  },
  {
    id: 2,
    projectId: 1,
    unitNo: "A-102",
    type: "2 BHK",
    floor: 1,
    block: "A",
    size: "980 sq ft",
    price: "$385,000",
    status: "Booked",
    facing: "Street",
  },
  {
    id: 3,
    projectId: 1,
    unitNo: "A-201",
    type: "2 BHK",
    floor: 2,
    block: "A",
    size: "1000 sq ft",
    price: "$390,000",
    status: "Available",
    facing: "Park",
  },
  {
    id: 4,
    projectId: 1,
    unitNo: "A-202",
    type: "3 BHK",
    floor: 2,
    block: "A",
    size: "1400 sq ft",
    price: "$530,000",
    status: "Sold",
    facing: "Street",
  },
  {
    id: 5,
    projectId: 1,
    unitNo: "B-101",
    type: "1 BHK",
    floor: 1,
    block: "B",
    size: "700 sq ft",
    price: "$260,000",
    status: "Available",
    facing: "Garden",
  },
  {
    id: 6,
    projectId: 2,
    unitNo: "C-101",
    type: "1 BHK",
    floor: 1,
    block: "C",
    size: "650 sq ft",
    price: "$225,000",
    status: "Available",
    facing: "River",
  },
  {
    id: 7,
    projectId: 2,
    unitNo: "C-102",
    type: "2 BHK",
    floor: 1,
    block: "C",
    size: "950 sq ft",
    price: "$355,000",
    status: "Sold",
    facing: "Garden",
  },
  {
    id: 8,
    projectId: 3,
    unitNo: "T1-101",
    type: "Office Space",
    floor: 1,
    block: "T1",
    size: "1200 sq ft",
    price: "$580,000",
    status: "Available",
    facing: "City",
  },
];

// Users
export const mockUsers = [
  {
    id: 1,
    name: "Amit Sharma",
    email: "amit.sharma@example.in",
    phone: "+91 98765 43210",
    role: "Admin",
    status: "Active",
    projects: ["Parkview Residences", "Riverside Apartments"],
    assignedLeads: 24,
    lastActive: "2023-05-18T10:30:00",
    password: "hashed_password_1",
  },
  {
    id: 2,
    name: "Neha Patel",
    email: "neha.patel@example.in",
    phone: "+91 91234 56789",
    role: "Sales Executive",
    status: "Active",
    projects: ["Riverside Apartments", "Skyline Towers"],
    assignedLeads: 18,
    lastActive: "2023-05-18T09:15:00",
    password: "hashed_password_2",
  },
  {
    id: 3,
    name: "Rajeev Menon",
    email: "rajeev.menon@example.in",
    phone: "+91 99887 66554",
    role: "Sales Executive",
    status: "Active",
    projects: ["Parkview Residences", "Skyline Towers"],
    assignedLeads: 15,
    lastActive: "2023-05-17T16:45:00",
    password: "hashed_password_3",
  },
  {
    id: 4,
    name: "Priya Desai",
    email: "priya.desai@example.in",
    phone: "+91 98700 11223",
    role: "Manager",
    status: "Active",
    projects: ["All Projects"],
    assignedLeads: 8,
    lastActive: "2023-05-18T11:20:00",
    password: "hashed_password_4",
  },
  {
    id: 5,
    name: "Rohan Verma",
    email: "rohan.verma@example.in",
    phone: "+91 98675 44332",
    role: "Sales Executive",
    status: "Inactive",
    projects: ["Parkview Residences"],
    assignedLeads: 0,
    lastActive: "2023-04-30T15:10:00",
    password: "hashed_password_5",
  },
];


// Documents
export const mockDocuments = [
  {
    id: 1,
    name: "Parkview Floor Plan.pdf",
    type: "Floor Plan",
    project: "Parkview Residences",
    projectId: 1,
    size: "2.4 MB",
    uploadedBy: "Alex Johnson",
    uploadedById: 1,
    uploadedOn: "2023-05-15",
    status: "Verified",
    lead: null,
    leadId: null,
    url: "https://example.com/documents/parkview-floor-plan.pdf",
  },
  {
    id: 2,
    name: "Riverside Brochure.pdf",
    type: "Brochure",
    project: "Riverside Apartments",
    projectId: 2,
    size: "4.7 MB",
    uploadedBy: "Michael Chen",
    uploadedById: 2,
    uploadedOn: "2023-05-14",
    status: "Verified",
    lead: null,
    leadId: null,
    url: "https://example.com/documents/riverside-brochure.pdf",
  },
  {
    id: 3,
    name: "John Smith ID.jpg",
    type: "Identity Document",
    project: null,
    projectId: null,
    size: "1.2 MB",
    uploadedBy: "Alex Johnson",
    uploadedById: 1,
    uploadedOn: "2023-05-12",
    status: "Verified",
    lead: "John Smith",
    leadId: 1,
    url: "https://example.com/documents/john-smith-id.jpg",
  },
  {
    id: 4,
    name: "Sarah Johnson Bank Statement.pdf",
    type: "Financial",
    project: null,
    projectId: null,
    size: "3.5 MB",
    uploadedBy: "Jessica Lee",
    uploadedById: 3,
    uploadedOn: "2023-05-10",
    status: "Pending",
    lead: "Sarah Johnson",
    leadId: 2,
    url: "https://example.com/documents/sarah-johnson-bank-statement.pdf",
  },
  {
    id: 5,
    name: "Skyline Towers Construction Update.docx",
    type: "Report",
    project: "Skyline Towers",
    projectId: 3,
    size: "1.8 MB",
    uploadedBy: "David Martinez",
    uploadedById: 4,
    uploadedOn: "2023-05-08",
    status: "Verified",
    lead: null,
    leadId: null,
    url: "https://example.com/documents/skyline-towers-construction-update.docx",
  },
  {
    id: 6,
    name: "Michael Brown Contract.pdf",
    type: "Legal",
    project: "Parkview Residences",
    projectId: 1,
    size: "2.2 MB",
    uploadedBy: "Alex Johnson",
    uploadedById: 1,
    uploadedOn: "2023-05-05",
    status: "Pending",
    lead: "Michael Brown",
    leadId: 3,
    url: "https://example.com/documents/michael-brown-contract.pdf",
  },
];

// Site Visits
export const mockSiteVisits = [
  {
    id: 1,
    leadId: 1,
    leadName: "John Smith",
    projectId: 1,
    projectName: "Parkview Residences",
    date: "2023-05-22",
    time: "11:00 AM",
    status: "Scheduled",
    executiveId: 1,
    executiveName: "Alex Johnson",
    notes: "Client interested in 3 BHK units with park view.",
  },
  {
    id: 2,
    leadId: 3,
    leadName: "Michael Brown",
    projectId: 1,
    projectName: "Parkview Residences",
    date: "2023-05-20",
    time: "2:30 PM",
    status: "Completed",
    executiveId: 1,
    executiveName: "Alex Johnson",
    notes:
      "Client liked the 4 BHK model. Interested in floor plans and pricing.",
  },
  {
    id: 3,
    leadId: 2,
    leadName: "Sarah Johnson",
    projectId: 2,
    projectName: "Riverside Apartments",
    date: "2023-05-25",
    time: "10:00 AM",
    status: "Scheduled",
    executiveId: 2,
    executiveName: "Michael Chen",
    notes: "Investment buyer. Interested in rental yield information.",
  },
  {
    id: 4,
    leadId: 4,
    leadName: "Emily Davis",
    projectId: 3,
    projectName: "Skyline Towers",
    date: "2023-05-18",
    time: "4:00 PM",
    status: "Completed",
    executiveId: 3,
    executiveName: "Jessica Lee",
    notes: "Client very interested in high floor units with city view.",
  },
  {
    id: 5,
    leadId: 6,
    leadName: "Jennifer Taylor",
    projectId: 3,
    projectName: "Skyline Towers",
    date: "2023-05-27",
    time: "1:00 PM",
    status: "Scheduled",
    executiveId: 3,
    executiveName: "Jessica Lee",
    notes: "Client will bring her dogs to check pet-friendly amenities.",
  },
];

// Dashboard Stats
export const mockDashboardStats = {
  totalLeads: 1284,
  leadGrowth: 12.5,
  conversionRate: 24.8,
  conversionGrowth: 3.2,
  activeProjects: 8,
  projectGrowth: 0,
  revenue: "$1.2M",
  revenueGrowth: 18.3,
  leadsBySource: [
    { source: "Website", count: 450 },
    { source: "Facebook", count: 320 },
    { source: "Instagram", count: 280 },
    { source: "Google", count: 150 },
    { source: "Referral", count: 84 },
  ],
  leadsByStatus: [
    { status: "New", count: 320 },
    { status: "Contacted", count: 280 },
    { status: "Site Visit", count: 240 },
    { status: "Negotiation", count: 180 },
    { status: "Won", count: 190 },
    { status: "Lost", count: 74 },
  ],
  revenueData: {
    week: [
      { date: "Mon", amount: 45000 },
      { date: "Tue", amount: 52000 },
      { date: "Wed", amount: 49000 },
      { date: "Thu", amount: 63000 },
      { date: "Fri", amount: 55000 },
      { date: "Sat", amount: 70000 },
      { date: "Sun", amount: 42000 },
    ],
    month: [
      { date: "Week 1", amount: 280000 },
      { date: "Week 2", amount: 320000 },
      { date: "Week 3", amount: 290000 },
      { date: "Week 4", amount: 310000 },
    ],
    quarter: [
      { date: "Jan", amount: 900000 },
      { date: "Feb", amount: 850000 },
      { date: "Mar", amount: 950000 },
    ],
    year: [
      { date: "Q1", amount: 2700000 },
      { date: "Q2", amount: 3100000 },
      { date: "Q3", amount: 2900000 },
      { date: "Q4", amount: 3300000 },
    ],
  },
  recentLeads: mockLeads.slice(0, 5),
  upcomingFollowUps: [
    {
      id: 1,
      leadName: "John Smith",
      date: "2023-05-22",
      time: "11:00 AM",
      type: "Site Visit",
      project: "Parkview Residences",
    },
    {
      id: 2,
      leadName: "Sarah Johnson",
      date: "2023-05-23",
      time: "2:30 PM",
      type: "Call",
      project: "Riverside Apartments",
    },
    {
      id: 3,
      leadName: "Jennifer Taylor",
      date: "2023-05-24",
      time: "10:00 AM",
      type: "Email",
      project: "Skyline Towers",
    },
    {
      id: 4,
      leadName: "Michael Brown",
      date: "2023-05-25",
      time: "4:00 PM",
      type: "Meeting",
      project: "Parkview Residences",
    },
  ],
};

// Notifications
export const mockNotifications = [
  {
    id: 1,
    type: "lead",
    message: "New lead assigned: John Smith",
    date: "2023-05-18T10:30:00",
    read: false,
    link: "/leads/1",
  },
  {
    id: 2,
    type: "visit",
    message: "Site visit scheduled with Sarah Johnson",
    date: "2023-05-17T14:45:00",
    read: false,
    link: "/site-visits",
  },
  {
    id: 3,
    type: "document",
    message: "Document uploaded: Floor Plan.pdf",
    date: "2023-05-16T09:20:00",
    read: true,
    link: "/documents",
  },
  {
    id: 4,
    type: "project",
    message: "Project status updated: Skyline Towers",
    date: "2023-05-15T16:10:00",
    read: true,
    link: "/projects/3",
  },
  {
    id: 5,
    type: "lead",
    message: "Lead status changed: Michael Brown (Site Visit)",
    date: "2023-05-14T11:05:00",
    read: true,
    link: "/leads/3",
  },
];
